#!/usr/bin/env bash
#
# Refresh the vendored browser assets in static/vendor/.
#
# These files are compiled into the binary with include_bytes!, so the served
# page never contacts a CDN — a webshell page is a root-capable terminal, and
# a third-party script tag on it is a remote-code-execution dependency.
#
# Assets come from the npm registry and every tarball is checked against the
# integrity hash npm published for that exact version. Note that a CDN's
# ".min.js" is NOT always what the package author shipped: jsdelivr re-minifies
# on the fly, so its bytes differ from the tarball. We take the tarball.
#
# Usage:
#   ./update_js.sh                 # re-fetch the pinned versions below
#   ./update_js.sh --check         # verify static/vendor matches upstream, no writes
#   XTERM_VERSION=5.6.0 ./update_js.sh
#
# After updating, rebuild so the new bytes land in the binary:  cargo build --release

set -euo pipefail

XTERM_VERSION="${XTERM_VERSION:-6.0.0}"
ADDON_FIT_VERSION="${ADDON_FIT_VERSION:-0.11.0}"

cd "$(dirname "$0")"
VENDOR="static/vendor"
CHECK_ONLY=0
[ "${1:-}" = "--check" ] && CHECK_ONLY=1

for tool in curl tar sha256sum sha512sum base64 python3; do
  command -v "$tool" >/dev/null || { echo "missing required tool: $tool" >&2; exit 1; }
done

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# fetch <name> <version> <path-in-tarball> <dest-basename>
fetch() {
  local name="$1" version="$2" src="$3" dest="$4"
  echo "==> $name@$version"

  local meta tarurl integrity tarball computed
  meta="$(curl -fsSL --max-time 120 "https://registry.npmjs.org/${name}/${version}")"
  tarurl="$(printf '%s' "$meta" | python3 -c 'import sys,json; print(json.load(sys.stdin)["dist"]["tarball"])')"
  integrity="$(printf '%s' "$meta" | python3 -c 'import sys,json; print(json.load(sys.stdin)["dist"].get("integrity",""))')"

  tarball="$WORK/$(basename "$tarurl")"
  curl -fsSL --max-time 300 -o "$tarball" "$tarurl"

  # npm publishes dist.integrity as "sha512-<base64>" over the tarball bytes.
  computed="sha512-$(sha512sum "$tarball" | cut -d' ' -f1 | xxd -r -p | base64 -w0)"
  if [ -z "$integrity" ]; then
    echo "    WARNING: npm published no integrity hash for this version" >&2
  elif [ "$integrity" != "$computed" ]; then
    echo "    INTEGRITY MISMATCH -- refusing to vendor" >&2
    echo "      published: $integrity" >&2
    echo "      computed : $computed" >&2
    exit 1
  else
    echo "    tarball integrity OK"
  fi

  local ex="$WORK/ex-$dest"
  mkdir -p "$ex"
  tar -xzf "$tarball" -C "$ex"
  [ -f "$ex/package/$src" ] || { echo "    $src not found in tarball" >&2; exit 1; }

  local sum
  sum="$(sha256sum "$ex/package/$src" | cut -d' ' -f1)"
  if [ "$CHECK_ONLY" = 1 ]; then
    if [ -f "$VENDOR/$dest" ] && cmp -s "$ex/package/$src" "$VENDOR/$dest"; then
      echo "    $dest up to date ($sum)"
    else
      echo "    $dest DIFFERS from upstream" >&2
      DRIFT=1
    fi
  else
    mkdir -p "$VENDOR"
    cp "$ex/package/$src" "$VENDOR/$dest"
    echo "    wrote $VENDOR/$dest ($(wc -c < "$VENDOR/$dest") bytes, sha256 $sum)"
    printf '%s@%s  %s  sha256:%s\n' "$name" "$version" "$dest" "$sum" >> "$WORK/manifest"
  fi

  # Keep the upstream licence alongside the code we redistribute.
  if [ "$CHECK_ONLY" = 0 ] && [ -f "$ex/package/LICENSE" ]; then
    cp "$ex/package/LICENSE" "$VENDOR/LICENSE.$(printf '%s' "$name" | tr '/@' '__')"
  fi
}

DRIFT=0
fetch "@xterm/xterm"     "$XTERM_VERSION"     "lib/xterm.js"     "xterm.js"
fetch "@xterm/xterm"     "$XTERM_VERSION"     "css/xterm.css"    "xterm.css"
fetch "@xterm/addon-fit" "$ADDON_FIT_VERSION" "lib/addon-fit.js" "addon-fit.js"

if [ "$CHECK_ONLY" = 1 ]; then
  [ "$DRIFT" = 0 ] && echo "vendor tree matches upstream" || { echo "vendor tree is out of date" >&2; exit 1; }
  exit 0
fi

{
  echo "# Generated by update_js.sh -- do not edit by hand."
  echo "# Verified against the npm registry's published dist.integrity."
  cat "$WORK/manifest"
} > "$VENDOR/MANIFEST"

echo
echo "vendored:"
sed 's/^/  /' "$VENDOR/MANIFEST"
echo
echo "now rebuild so the binary picks them up:  cargo build --release"
